### ISSUE TITLE
features.ejs update

### ISSUE THREAD

**Issue by C0rrupted0mn1p0tence** [ShinobiCCTV/shinobi.video#2]
"WebM Recording (Modern)" currently reads: 
"WebM is special because the files are super compressed. The drawback is how much CPU is used to **created** them and is not playable on all modern mobile devices without third-party programs **,** like VLC.

"Created" should be "create" and you don't need the comma before "like VLC".

Nice job so far.

**Comment by moeiscool** [comment]
thanks :D i made the changes

**Comment by C0rrupted0mn1p0tence** [comment]
Very fast :+1:
